# This is a basic workflow to help you get started with Actions

name: Hugo Build

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
    - master

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Check out master branch
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        uses: actions/checkout@master
      - name: Build Hugo
        uses: jakejarvis/hugo-build-action@master
      - name: Push to Github
        uses: dciborow/commit@0.0.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          push-branch: 'master'
          commit-message: 'Built with GitHub Actions'
          force-push: 'true'
          files: docs/
          name: Guillaume Blackburn
          email: guillaume.blackburn1@gmail.com
